dist: xenial
language: python
python: 3.8
addons:
  apt:
    packages:
      - xsel
matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - env: TOX_ENV=py38
    - python: 3.9-dev
      env: TOX_ENV=py39
    - env: TOX_ENV=flake8
    - env: TOX_ENV=pyroma
    - env: TOX_ENV=check-manifest
cache: pip
install:
  - pip install --upgrade pip
  - pip install tox tox-travis
services:
  - xvfb
script: tox -e $TOX_ENV
